apiVersion: apps/v1
kind: Deployment

metadata:
  name: webappcal

spec:
  replicas: 2
  selector:
    matchLabels:
      app: webappcal

  template:
    metadata:
      labels:
        app: webappcal

    spec:
      containers:
      - name: webappcal
        image: derao/webappcal
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webappcal-service
spec:
  selector:
    app: webappcal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

